/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XSmartAppBanner {
        "appStoreRating": number;
        "appStoreURI": string;
        "appStoreURL": string;
        "author": string;
        "description": string;
        "favicon": string;
        "name": string;
        "playStoreRating": number;
        "playStoreURI": string;
        "playStoreURL": string;
    }
}
declare global {
    interface HTMLXSmartAppBannerElement extends Components.XSmartAppBanner, HTMLStencilElement {
    }
    var HTMLXSmartAppBannerElement: {
        prototype: HTMLXSmartAppBannerElement;
        new (): HTMLXSmartAppBannerElement;
    };
    interface HTMLElementTagNameMap {
        "x-smart-app-banner": HTMLXSmartAppBannerElement;
    }
}
declare namespace LocalJSX {
    interface XSmartAppBanner {
        "appStoreRating"?: number;
        "appStoreURI"?: string;
        "appStoreURL"?: string;
        "author"?: string;
        "description"?: string;
        "favicon"?: string;
        "name"?: string;
        "playStoreRating"?: number;
        "playStoreURI"?: string;
        "playStoreURL"?: string;
    }
    interface IntrinsicElements {
        "x-smart-app-banner": XSmartAppBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "x-smart-app-banner": LocalJSX.XSmartAppBanner & JSXBase.HTMLAttributes<HTMLXSmartAppBannerElement>;
        }
    }
}
